<?php include 'inc/head.php'; ?>
    
    <body>

        <div id="main-content" class="container-fluid">
            <div class="container">     
                
                <div id="hero" class="row justify-content-md-center pt-5 pb-4">
                    <div class="col-sm-12 col-md-8 text-center">
                        <h4 class="tool-name text-uppercase">ROI Calculator</h5>
                        <h1 class="mb-4">Concur Expense ROI Calculator</h1>
                        <p>Etiam porta sem malesuada magna mollis euismod. Curabitur blandit tempus porttitor. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div><!--// .col-sm-12 -->
                </div><!--// .row -->         

                <div class="row">

                    <div id="calculator" class="col-md-7">

                        <h3 class="mb-4">Your company details</h3>

                        <div id="company-info" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingOne">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#company-info" href="#collapseOne" class="category-title p-4 collapsed" aria-expanded="true" aria-controls="collapseOne">
                                            Company info
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="row px-4 pb-4">

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
                                                'How many employees in your company?', //question
        										'1', // min
        										'1000', // max 
        										'1', // step
        										'650', // value
        										'# of employees', // unit
                                                'employee_count' // id
        									); 
        								?>
								
							         </div><!-- // .row -->                              
                                </div><!--// .panel-collapse -->

                                <!-- EVAN-07: code reuse. -->
                                <div id="reverseCollapseOne" class="reverse-collapse">
                                    <div>How many employees in your company? <span id="extra-employee_count">650</span></div>
                                </div>

                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                        <div id="employee-expense-distribution" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingTwo">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#employee-expense-distribution" href="#collapseTwo" class="category-title p-4" aria-expanded="true" aria-controls="collapseTwo">
                                            Employee expense and distribution
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseTwo" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="headingTwo">
                                    
                                    <div class="row px-4 pb-4">

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'How many expense report filers do you have?', //question
										'1', // min
										'50', // max 
										'1', // step
										'20', // value
										'# of filers', // unit
                                        'expense_count' // id
									); 
								?>

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Number of expense reports per filer/month?', //question
										'1', // min
										'50', // max 
										'1', // step
										'2', // value
										'# reports/month', // unit
                                        'expense_per_month' // id
									); 
								?>

                                    </div><!--// .row -->                                  

                                </div><!--// .panel-collapse -->

                                <!-- EVAN-01: just some divs right now -->
                                <!-- EVAN-05: "expense_count" and "20" are repeated here, unfortuantely. Same goes for expenses per month. -->
                                <div id="reverseCollapseTwo" class="reverse-collapse start-as-hidden">
                                    <div>How many expense report filers do you have? <span id="extra-expense_count">20</span></div>
                                    <div>Number of expense reports per filer/month? <span id="extra-expense_per_month">2</span></div>
                                </div>
                                
                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                        <div id="losses-fraud-violations" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingThree">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#losses-fraud-violations" href="#collapseThree" class="category-title p-4" aria-expanded="true" aria-controls="collapseThree">
                                            Loss due to fraud and violations
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseThree" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="headingThree">
                                    
                                     <div class="row px-4 pb-4">

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Percentage of spend that is out of policy?', //question
										'0', // min
										'100', // max 
										'1', // step
										'20', // value
										'# of employees', // unit
                                        'out_of_spend_percent' // id
									); 
								?>  

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Percentage of travelers who pad their expense report?', //question
										'0', // min
										'50', // max 
										'1', // step
										'17', // value
										'# of employees', // unit
                                        'report_pad_percent' // id
									); 
								?>  
                                    
                                    </div><!--// .row -->

                                    <div class="row px-4 pb-4">

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Average amount fraudulently claimed?', //question
										'5', // min
										'1000', // max 
										'1', // step
										'50', // value
										'# of employees', // unit
                                        'fraud_average' // id
									); 
								?> 

                                    </div><!--// .row -->                         

                                </div><!--// .panel-collapse -->
                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                        <div id="time-effort" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingFour">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#time-effort" href="#collapseFour" class="category-title p-4" aria-expanded="true" aria-controls="collapseFour">
                                            Time and effort
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseFour" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="headingFour">
                                    
                                    <div class="row px-4 pb-4">

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Time it takes to create an expense report?', //question
										'1', // min
										'100', // max 
										'1', // step
										'5', // value
										'min', // unit
                                        'expense_time' // id
									); 
								?> 

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Time it takes a manager to review and approve each report?', //question
										'1', // min
										'100', // max 
										'1', // step
										'11', // value
										'min', // unit
                                        'review_time' // id
									); 
								?> 

                                    </div><!--// .row -->

                                    <div class="row px-4 pb-4">

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Time it takes for a back office employee to review and approve?', //question
										'1', // min
										'100', // max 
										'1', // step
										'20', // value
										'min', // unit
                                        'back_employee_time' // id
									); 
								?> 

								<?php echo question(
                                        1, // Wrap in BS column? (bool)
										'Time it takes to create a reimbursement check?', //question
										'1', // min
										'100', // max 
										'1', // step
										'20', // value
										'min', // unit
                                        'reimbursement_time' // id
									); 
								?>
                                        
                                    </div><!--// .row -->

                                </div><!--// .panel-collapse -->
                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                    </div><!--// #calculator.col-sm-7 -->

                    <?php include 'inc/sidebar-uncookied.inc'; ?>

                </div><!--// .row -->
            </div><!--// .container -->

            <div class="spacer m-5"></div>

            <!-- Form -->
            <div id="form" class="hidden container py-5">
                <div class="row">
                    
                    <div class="col-sm-12 col-md-5">
                        <h5>Receive your ROI results</h5>
                        <p>In the real experience, this form will function the same as a premium asset form. For this prototype, you do not need to fill out any of the fields, instead just click the submit button.</p>
                    </div><!--// .col-sm-4 -->
                    <div class="col-sm-12 col-md-7 mt-sm-4">
                        <form class="premium-form">
                            <div class="form-group row">
                                
                                <div class="col-sm-6">
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="First Name">
                                    </fieldset>
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput3" placeholder="Company Name">
                                    </fieldset>                                
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput5" placeholder="Postal Code">
                                    </fieldset>            
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput7" placeholder="Phone Number">
                                    </fieldset>
                                </div><!--// .col-sm-6 -->

                                <div class="col-sm-6">
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Last Name">
                                    </fieldset>         
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput4" placeholder="Number of Employees">
                                    </fieldset> 
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput6" placeholder="USA">
                                    </fieldset>
                                    <fieldset class="form-group">
                                        <input type="text" class="form-control" id="formGroupExampleInput8" placeholder="Business Email">
                                    </fieldset>
                                </div><!--// .col-sm-6 -->

                            </div>
                            
                            <div class="form-group row">
                                <div class="col-sm-12 mb-3">
                                    <img src="img/recaptcha.png" />
                                </div>
                            </div><!--// .form-group.row -->

                            <div class="form-group row">
                                <div class="col-sm-12 mb-3">
                                    <div class="form-check form-check-inline" style="align-items: flex-start;">
                                        <input class="form-check-input mr-3 mt-1" type="checkbox" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                                        <label class="form-check-label" for="inlineRadio1">Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</label>
                                    </div>
                                </div>
                            </div><!--// .form-group.row -->

                            <a class="btn btn-primary" href="expense-roi-landing-results.phtml?[unique-hash]">Submit</a>

                        </form>
                    </div><!--// .col-sm-7 -->

                </div><!--// .row -->
            </div><!--// .container -->

        </div><!--// .container-fluid -->

        <?php echo placeholderModule('content', 'left', 'Placeholder module', 0); ?>
        <?php echo placeholderModule('content', 'right', 'Placeholder module', 0); ?>
        <?php echo placeholderModule('cta', '','Placeholder CTA', 1); ?>

        <?php include 'inc/footer-scripts.php'; ?>

    </body>
</html>
