<?php 
include 'inc/head.php'; 
$pageTitle = 'Concur Expense ROI Calculator'; // Call this in your pages' files to define the page title
?>
    
    <body id="uncookied-roi-landing">

        <div id="main-content" class="container-fluid">
            <div class="container">     
                
                <div id="hero" class="row justify-content-md-center pt-5 pb-4">
                    <div class="col-sm-12 col-md-8 text-center">
                        <h4 class="tool-name text-uppercase">ROI Calculator</h5>
                        <h1 class="mb-4">Concur Expense ROI Calculator</h1>
                        <p>Etiam porta sem malesuada magna mollis euismod. Curabitur blandit tempus porttitor. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div><!--// .col-sm-12 -->
                </div><!--// .row -->         

                <div class="row">

                    <div id="calculator" class="col-md-7">

                        <h3 class="mb-4">Your company details</h3>

                        <div id="company-info" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingOne">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#company-info" href="#collapseOne" class="category-title p-4 collapsed" aria-expanded="true" aria-controls="collapseOne">
                                            Company info
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="row px-4">

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
                                                'How many employees in your company?', //question
        										'1', // min
        										'1000', // max 
        										'1', // step
        										'650', // value
        										'# of employees', // unit
                                                'employee_count' // id
        									); 
        								?>
								
							         </div><!-- // .row -->                              
                                </div><!--// .panel-collapse -->

                                <div id="reverseCollapseOne" class="reverse-collapse container">
                                    
                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>How many employees in your company?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-employee_count" class="collapsed-value">650</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->

                                </div><!--// .reverse-collapse -->

                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                        <div id="employee-expense-distribution" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingTwo">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#employee-expense-distribution" href="#collapseTwo" class="category-title p-4" aria-expanded="true" aria-controls="collapseTwo">
                                            Employee expense and distribution
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseTwo" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="headingTwo">
                                    
                                    <div class="row px-4">

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'How many expense report filers do you have?', //question
        										'1', // min
        										'50', // max 
        										'1', // step
        										'20', // value
        										'# of filers', // unit
                                                'expense_count' // id
        									); 
        								?>

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Number of expense reports per filer/month?', //question
        										'1', // min
        										'50', // max 
        										'1', // step
        										'2', // value
        										'# reports/month', // unit
                                                'expense_per_month' // id
        									); 
        								?>

                                    </div><!--// .row -->                                  

                                </div><!--// .panel-collapse -->

                                <div id="reverseCollapseTwo" class="reverse-collapse container start-as-hidden">
                                    
                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>How many expense report filers do you have?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-expense_count" class="collapsed-value">20</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->   

                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Number of expense reports per filer/month?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-expense_per_month" class="collapsed-value">2</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->  

                                </div><!--// .reverse-collapse -->
                                
                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                        <div id="losses-fraud-violations" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingThree">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#losses-fraud-violations" href="#collapseThree" class="category-title p-4" aria-expanded="true" aria-controls="collapseThree">
                                            Loss due to fraud and violations
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseThree" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="headingThree">
                                    
                                     <div class="row px-4">

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Percentage of spend that is out of policy?', //question
        										'0', // min
        										'100', // max 
        										'1', // step
        										'20', // value
        										'%', // unit
                                                'out_of_spend_percent' // id
        									); 
        								?>  

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Percentage of travelers who pad their expense report?', //question
        										'0', // min
        										'50', // max 
        										'1', // step
        										'17', // value
        										'%', // unit
                                                'report_pad_percent' // id
        									); 
        								?>  
                                    
                                    </div><!--// .row -->

                                    <div class="row px-4">

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Average amount fraudulently claimed?', //question
        										'5', // min
        										'1000', // max 
        										'1', // step
        										'50', // value
        										'$ claimed', // unit
                                                'fraud_average' // id
        									); 
        								?> 

                                    </div><!--// .row -->                         

                                </div><!--// .panel-collapse -->

                                <div id="reverseCollapseThree" class="reverse-collapse container start-as-hidden">
                                    
                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Percentage of spend that is out of policy?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-out_of_spend_percent" class="collapsed-value">20</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row --> 

                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Percentage of travelers who pad their expense report?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-report_pad_percent" class="collapsed-value">17</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->

                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Average amount fraudulently claimed?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-fraud_average" class="collapsed-value">50</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->

                                </div><!--// .reverse-collapse -->

                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                        <div id="time-effort" class="category-container border--lt-grey" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingFour">
                                    <h3 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#time-effort" href="#collapseFour" class="category-title p-4" aria-expanded="true" aria-controls="collapseFour">
                                            Time and effort
                                        </a>
                                    </h3>
                                </div>
                                <div id="collapseFour" class="panel-collapse collapse show" role="tabpanel" aria-labelledby="headingFour">
                                    
                                    <div class="row px-4">

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Time it takes to create an expense report?', //question
        										'1', // min
        										'100', // max 
        										'1', // step
        										'5', // value
        										'min', // unit
                                                'expense_time' // id
        									); 
        								?> 

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Time it takes a manager to review and approve each report?', //question
        										'1', // min
        										'100', // max 
        										'1', // step
        										'11', // value
        										'min', // unit
                                                'review_time' // id
        									); 
        								?> 

                                    </div><!--// .row -->

                                    <div class="row px-4">

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Time it takes for a back office employee to review and approve?', //question
        										'1', // min
        										'100', // max 
        										'1', // step
        										'20', // value
        										'min', // unit
                                                'back_employee_time' // id
        									); 
        								?> 

        								<?php echo question(
                                                1, // Wrap in BS column? (bool)
        										'Time it takes to create a reimbursement check?', //question
        										'1', // min
        										'100', // max 
        										'1', // step
        										'20', // value
        										'min', // unit
                                                'reimbursement_time' // id
        									); 
        								?>
                                        
                                    </div><!--// .row -->

                                </div><!--// .panel-collapse -->

                                <div id="reverseCollapseFour" class="reverse-collapse container start-as-hidden">
                                    
                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Time it takes to create an expense report?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-expense_time" class="collapsed-value">5</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row --> 

                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Time it takes a manager to review and approve each report?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-review_time" class="collapsed-value">11</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->

                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Time it takes for a back office employee to review and approve?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-back_employee_time" class="collapsed-value">20</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->

                                    <div class="d-flex align-items-center row p-2">
                                        <div class="col-sm-10">
                                            <p>Time it takes to create a reimbursement check?</p>
                                        </div><!--// .col-sm-10 -->
                                        <div class="col-sm-2 text-sm-right">
                                            <span id="extra-reimbursement_time" class="collapsed-value">20</span>
                                        </div><!--// .col-sm-2 -->
                                    </div><!--// .row -->

                                </div><!--// .reverse-collapse -->

                            </div><!--// .panel -->
                        </div><!--// .category-container.border--lt-grey -->

                    </div><!--// #calculator.col-sm-7 -->

                    <?php include 'inc/sidebar-results.inc'; ?>

                </div><!--// .row -->
            </div><!--// .container -->

            <div class="spacer m-5"></div>

        </div><!--// .container-fluid -->

        <?php include 'inc/share-buttons.inc'; ?>

        <?php //echo placeholderModule('content', 'left', 'Placeholder module', 0); ?>
        <?php //echo placeholderModule('content', 'right', 'Placeholder module', 0); ?>
        <?php echo placeholderModule('cta', '','Placeholder CTA', 1); ?>

        <?php include 'inc/footer-scripts.php'; ?>

        <script>
            // If user chose cookied version, change button link to point to cookied ROI Landing page
            var x = getCookie('formcookie');
            if (x) {
                console.log('cookie found!');
                $('#pass-cookie').text('Calculate ROI').attr('href', 'expense-roi-landing-results.phtml').removeAttr('download');
            }        
        </script>

    </body>
</html>
<?
$pageContents = ob_get_contents (); // Get all the page's HTML into a string
ob_end_clean (); // Wipe the buffer

// Replace <!--TITLE--> with $pageTitle variable contents, and print the HTML
echo str_replace ('<!--TITLE-->', $pageTitle, $pageContents);
?>
