<?php 
    $header = false;
    $footer = false;
    include 'inc/head.php'; 
    $pageTitle = '*Select Cookies*'; // Call this in your pages' files to define the page title
?>

    <body>

        <div id="main-content" class="container-fluid py-5">
            <div class="container">              
                
                <div class="row justify-content-sm-center mb-4">
                   
                   <div class="col-sm-8 text-center">
                        <h4>Your experience with the ROI calculator will differ based on whether you have previously fill out a form on concur.com</h4>
                        <h5>This screen is for demo purposes only. Please choose your experience below: </h5>
                    </div><!--// .col-sm -->

                </div><!--// .row -->

                <div class="row justify-content-sm-center">
                   
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            
                            <h5 class="mb-4">I am a user that <span class="highlight">HAS</span> previously filled out a form on concur.com</h5>
                            <a class="btn btn-primary align-bottom" href="roi-module.phtml">Uncookied experience</a>

                        </div><!--// .border--lt-grey -->
                    </div><!--// .col-sm-4 -->

                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">

                            <h5 class="mb-4">I am a user that <span class="highlight">HAS NOT</span> previously filled out a form on concur.com</h5>
                            <a id="pass-cookie" class="btn btn-primary" href="roi-module.phtml">Cookied experience</a>

                        </div><!--// .border--lt-grey -->    
                    </div><!--// .col-sm-4 -->

                </div><!--// .row -->

            </div><!--// .container -->
        </div><!--// .container-fluid -->

        <?php include 'inc/footer-scripts.php'; ?>

        <script>
            // Pass 'form' cookie if user chooese cookied version
            $( '#pass-cookie' ).click(function() {
                setCookie('formcookie','testcookie',7);
            });
        </script>
        
    </body>
</html>
<?
$pageContents = ob_get_contents (); // Get all the page's HTML into a string
ob_end_clean (); // Wipe the buffer

// Replace <!--TITLE--> with $pageTitle variable contents, and print the HTML
echo str_replace ('<!--TITLE-->', $pageTitle, $pageContents);
?>