<?php include 'inc/head.php' ?>

    <body>

        <div class="container-fluid module">
            <div class="container">              
                <div class="row text-center">
                    <h2 class="text-center">Choose your experience:</h2>
                </div>
                <div class="row">
                    <ul class="list-unstyled">
                        <li><a class="btn btn-primary mb-2" href="uncookied.phtml">Uncookied</a></li>
                        <li><a class="btn btn-primary" href="cookied.phtml">Cookied</a></li>
                    </ul>
                </div>

                </div><!--// .row -->
            </div><!--// .container -->
        </div><!--// .container-fluid -->

        <?php include 'inc/footer-scripts.inc'; ?>
        
    </body>
</html>
