<?php include 'inc/head.php' ?>

    <body>

        <div id="main-content" class="container-fluid py-5">
            <div class="container">              
                
                <div class="row justify-content-sm-center mb-4">
                   
                   <div class="col-sm-8 text-center">
                        <h4>Your expense with the ROI calculator will differ based on whether you have previously fill out a form on concur.com</h4>
                        <h5>Please choose your experience below:</h5>
                    </div><!--// .col-sm -->

                </div><!--// .row -->

                <div class="row justify-content-sm-center">
                   
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            
                            <h5 class="mb-4">I am a user that <span class="highlight">HAS</span> previously filled out a form on concur.com</h5>
                            <a class="btn btn-primary align-bottom" href="module-uncookied.phtml">Uncookied experience</a>

                        </div><!--// .border--lt-grey -->
                    </div><!--// .col-sm-4 -->

                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">

                            <h5 class="mb-4">I am a user that <span class="highlight">HAS NOT</span> previously filled out a form on concur.com</h5>
                            <a class="btn btn-primary" href="module-cookied.phtml">Cookied experience</a>

                        </div><!--// .border--lt-grey -->    
                    </div><!--// .col-sm-4 -->

                </div><!--// .row -->

            </div><!--// .container -->
        </div><!--// .container-fluid -->

        <?php include 'inc/footer-scripts.inc'; ?>
        
    </body>
</html>
