<?php include 'inc/head.php' ?>

    <body>

        <div class="container-fluid module">
            <div class="container">
            
                <div class="row mb-5">
                    <div class="col-sm-7">
                        <h2 class="mt-0">Time is money. Discover how using Concur Expense can reduce time and expense related to filing an expense report with our <span class="highlight">ROI calculator.</span></h2>
                    </div><!--// .col-sm-7 -->
                    <div class="offset-sm-1 col-sm-4 align-self-center">
                        <img src="img/time-money-pictograms@2x.png" />
                    </div><!--// .col-sm-4 -->
                </div><!--// .row -->
                
                <div class="row">
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            <p>How many employees in your company?</p>
                            
                            <div class="range-wrap">
                                <input type="range" id="js-amount-range" class="sliderRange" min="5" max="1000" step="1" value="650">
                            </div><!--// .range-wrap -->

                            <div class="value-toggle">
                                <input type="number" id="js-amount-input" class="value-number" min="5" max="1000" step="1" value="650"></input>
                                <span class="value-unit"># of employees</span>
                            </div><!--// .value-toggle -->

                        </div><!--// .border--lt-grey -->
                    </div><!--// .col-sm-4 -->
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            <p>Typical number of expense reports filed per year</p>
                            <div class="value-outcome align-bottom">
                                <span id="value-number" class="value-number">2500</span><span class="value-unit"># reports filed</span>
                            </div><!--// .value-outcome -->
                        </div><!--// .border--lt-grey -->    
                    </div><!--// .col-sm-4 -->
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            <p>For a customized ROI report, please visit our ROI Calculator</p>
                            <a class="btn btn-primary align-bottom" href="expense-roi-landing-uncookied.phtml">Calculate your ROI</a>
                        </div><!--// .border--lt-grey -->    
                    </div><!--// .col-sm-4 -->
                </div><!--// .row -->

            </div><!--// .container -->
        </div><!--// .container-fluid -->

        <?php include 'inc/footer-scripts.inc'; ?>
        
    </body>
</html>
