<?php 
include 'inc/head.php'; 
?>

    <body>

        <?php echo placeholderModule('content', 'left', 'Placeholder module', 1); ?>

        <div id="main-content" class="container-fluid module">
            <div class="container">
            
                <div class="row mb-5">
                    <div class="col-sm-7">
                        <h2 class="mt-0">Time is money. Discover how using Concur Expense can reduce time and expense related to filing an expense report with our <span class="highlight">ROI calculator.</span></h2>
                    </div><!--// .col-sm-7 -->
                    <div class="offset-sm-1 col-sm-4 align-self-center">
                        <img src="img/time-money-pictograms@2x.png" />
                    </div><!--// .col-sm-4 -->
                </div><!--// .row -->
                
                <div class="row">
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            
                            <?php echo question(
                                    0, // Wrap in BS column? (bool)
                                    'How many employees in your company?', //question
                                    '5', // min
                                    '1000', // max 
                                    '1', // step
                                    '650', // value
                                    '# of employees', // unit
                                    'employee_count' // id
                                ); 
                            ?>

                        </div><!--// .border--lt-grey -->
                    </div><!--// .col-sm-4 -->
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            <p>Typical number of expense reports filed per year</p>
                            <div class="value-outcome align-bottom">
                                <span id="reports_filed" class="value-number">2,600</span><span class="value-unit"># reports filed</span>
                            </div><!--// .value-outcome -->
                        </div><!--// .border--lt-grey -->    
                    </div><!--// .col-sm-4 -->
                    <div class="col-sm-4">
                        <div class="border--lt-grey eq-height p-4">
                            <p>For a customized ROI report, please visit our ROI Calculator</p>
                            <a id="pass-cookie" class="btn btn-primary align-bottom" href="expense-roi-landing-uncookied.phtml">Calculate your ROI</a>
                        </div><!--// .border--lt-grey -->    
                    </div><!--// .col-sm-4 -->
                </div><!--// .row -->

            </div><!--// .container -->
        </div><!--// .container-fluid -->

        <?php echo placeholderModule('cta', '','Placeholder CTA', 1); ?>

        <?php include 'inc/footer-scripts.php'; ?>
        
        <script>
            //setCookie('formcookie','testcookie',7);

            var x = getCookie('formcookie');
            if (x) {
                $('#pass-cookie').attr("href", "expense-roi-landing-cookied.phtml")
            }        
        </script>
        
    </body>
</html>
