        <div class="container mb-5">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2 class="mb-4">Share this calculator</h2>
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="http://www.facebook.com/sharer.php?u=" target="_blank" title="Share this page on Facebook"><i class="fab fa-facebook-f"></i> Share</a></li>
                        <li class="list-inline-item"><a href="http://twitter.com/share?url=yo.com?text=Check" target="_blank" title="Tweet this page on Twitter"><i class="fab fa-twitter"></i> Tweet</a></li>
                        <li class="list-inline-item"><a href="http://www.linkedin.com/shareArticle?mini=true&url=YOUR_URL_to_share" target="_blank"><i class="fab fa-linkedin"></i> Linkedin</a></li>
                    </ul>
                    <div>
                        <input type="button" value="Copy Url" onclick="Copy();" /><textarea id="url" rows="1" cols="30"></textarea>
                    </div>
                </div><!--// .col-sm-12 -->
            </div><!--// .row -->
        </div><!--// .container -->