        <div class="container mb-5">
            <div class="justify-content-md-center row">
                
                <div class="col-sm-12 text-center">
                    <h2 class="mb-4">Share this calculator</h2>
			</div><!--// .col-sm-12 -->

			<div class="share-buttons col-sm-12 col-md-6">			
				<div class="row">
					<div class="col-sm-3 py-4 text-center">
						<a target="popup" href="https://facebook.com/sharer/sharer.php?" onclick="window.open('https://facebook.com/sharer/sharer.php?text=Try%20the%20new%20SAP%20Concur%20Expense%20ROI%20Calculator%20-%20','popup','width=600,height=600,scrollbars=no,resizable=no'); return false;"><i class="fab fa-facebook-f"></i>Facebook</a>
					</div>					
					<div class="col-sm-3 py-4 text-center">
						<a target="popup" href="https://twitter.com/share" onclick="window.open('https://twitter.com/share?text=Try%20the%20new%20SAP%20Concur%20Expense%20ROI%20Calculator%20-%20','popup','width=600,height=600,scrollbars=no,resizable=no'); return false;"><i class="fab fa-twitter"></i>Twitter</a>
					</div>
					<div class="col-sm-3 py-4 text-center">
						<a target="popup" href="https://www.linkedin.com/shareArticle" onclick="window.open('https://www.linkedin.com/shareArticle?mini=true&amp;url=http://localhost:8888/expense-roi-landing-uncookied.phtml&amp;title=Try%20the%20new%20SAP%20Concur%20Expense%20ROI%20Calculator%20-%20','popup','width=600,height=600,scrollbars=no,resizable=no'); return false;"><i class="fab fa-linkedin-in"></i>LinkedIn</a>
					</div>
					<div class="col-sm-3 py-4 text-center">
						<a target="popup" href="mailto:evan.lajambe@concur.com"><i class="far fa-envelope"></i>Email</a>
					</div>
				</div><!--// .row -->
				<div class="row">
					<div class="col-sm-12 py-4 text-center">
						<span href="#" onclick="Copy();" style="cursor: pointer;"><i class="far fa-clipboard"></i>Copy URL</span>
						<div>
							<textarea id="url" class="mt-3" rows="1" cols="30" style="width: 90%; text-align: center; resize: none;"></textarea>
						</div>
					</div>
				</div><!--// .row -->
               </div>
            </div><!--// .row -->
        </div><!--// .container -->


