                    <div id="sidebar" class="col-sm-5">
                        <div class="row no-gutters">
                            <div id="labor-savings" class="col-sm-6 text-center">
                                <div class="border--lt-grey eq-height p-4 br-0 bb-0 r-tl">
                                    <p>Yearly labor savings</p>
                                    <span class="value-number sm gold-text">25,000</span>
                                </div><!--// .border--lt-grey -->
                            </div><!--// .col-sm-6 -->

                            <div id="efficiency-increase" class="col-sm-6 text-center">
                                <div class="border--lt-grey eq-height p-4 bb-0 r-tr">
                                    <p>Efficiency increase</p>
                                    <span class="value-number sm gold-text">5%</span>
                                </div><!--// .border--lt-grey -->
                            </div><!--// .col-sm-6 -->
                        </div><!--// .row -->

                        <div class="row">
                            <div id="projected-roi" class="col-sm-12 text-center">
                                <div class="border--lt-gold eq-height p-4 r-br r-bl">
                                    <p>Estimated yearly ROI</p>
                                    <a href="#form" class="btn btn-primary ss">Calculate final ROI</a>
                                </div><!--// .border--lt-grey -->
                            </div><!--// .col-sm-12 -->
                        </div><!--// .row -->
                    </div><!--// #sidebar.col-sm-5 -->